### ISSUE TITLE
Feature request: remove dependency on pypandoc

### ISSUE THREAD

**Issue by jchristi** [coredumb/dns-blackhole#1]
I tried to install this with pip and get an error because I don't have pypandoc installed. To install it would add over 400mb of dependencies to my server. Please consider removing the dependency on pandoc. Thanks!

PS. Was about to create this exact same software myself when I came across your project! Love the idea!

**Comment by olivier-mauras** [comment]
You're right, the convenience of having it in the setup is not worth installing the deps.

**Comment by olivier-mauras** [comment]
Fixed: https://github.com/coredumb/dns-blackhole/commit/d2f0dfe7101abe12b315568419608699d03f2f7c
