### ISSUE TITLE
Blank zone added

### ISSUE THREAD

**Issue by jchristi** [coredumb/dns-blackhole#3]
Despite #2 , I am still getting an empty zone in the top of my `blacklist.zone` file:
```
local-zone: "" always_nxdomain
```
When this happens, I have to remove the empty zone and restart both unbound and firewalld before the hosts using the DNS server can regain internet access. I'm not sure what is causing the blank zone though, I would have thought my PR fixed it :frowning:

**Comment by olivier-mauras** [comment]
Indeed your PR should have fixed it ... 
Funny thing is I don't get this behaviour on several different installations and whitelists
Do you use additional list on top of the default ones?

Do you mind enabling some echos to see which domain ends up empty?

**Comment by olivier-mauras** [comment]
OK I've found the error, I'll commit the fix and a new PyPi package later today.

**Comment by olivier-mauras** [comment]
Fixed here: https://github.com/coredumb/dns-blackhole/commit/6b7610e259b3988957334efd8490d4575e5f3599
You must have a new line in your blacklist file which - cause of my lazy parsing - ended up as an empty domain.

Sorry about that. I've confirmed the fix, but please let me know if it works as expected for you.

**Comment by jchristi** [comment]
Confirmed. Works for me. Thanks!
